<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UI_Unilineal.Domain\UI_Unilineal.Domain.csproj" />
    <ProjectReference Include="..\UI_Unilineal.Engine\UI_Unilineal.Engine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
