<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia"
                      Version="11.3.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UI_Unilineal.Domain\UI_Unilineal.Domain.csproj" />
  </ItemGroup>

</Project>
