<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia"
                      Version="11.3.18" />

    <PackageReference Include="Avalonia.Desktop"
                      Version="11.3.18" />

    <PackageReference Include="Avalonia.Themes.Fluent"
                      Version="11.3.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UI_Unilineal.Domain\UI_Unilineal.Domain.csproj" />
    <ProjectReference Include="..\UI_Unilineal.Engine\UI_Unilineal.Engine.csproj" />
    <ProjectReference Include="..\UI_Unilineal.Export.Pdf\UI_Unilineal.Export.Pdf.csproj" />
    <ProjectReference Include="..\UI_Unilineal.Rendering.Avalonia\UI_Unilineal.Rendering.Avalonia.csproj" />
  </ItemGroup>

</Project>

